### ISSUE TITLE
Compiler error when using --with-static-eepp flag on Windows

### ISSUE THREAD

**Issue by sornian** [SpartanJ/eepp#15]
[os]:windows10 22H2
[visual studio]:2022 Version 17.3.6
[premake]:premake5
this is my steps

1.`git clone -b --recurse-submodules --depth=1 https://github.com/SpartanJ/eepp `(I try to clone tag:eepp-2.5.9 has same result )
2.open  premake5.lua and replace [https://www.libsdl.org/release/SDL2-devel-2.26.2-VC.zip] to [https://github.com/libsdl-org/SDL/releases/download/release-2.26.2/SDL2-devel-2.26.2-VC.zip]
3.premake5.exe --windows-vc-build --with-mojoal --with-static-eepp vs2022
4.open make\windows\eepp.sln and compile eepp-static success
5.I try to compile eepp-empty-window but has some error
the error message :

```Build started...
------ Build started: Project: eepp-empty-window, Configuration: release x64 ------
zlib.lib(inflate.obj) : error LNK2005: inflate already defined in zlib.lib(zlib1.dll)
zlib.lib(inflate.obj) : error LNK2005: inflateEnd already defined in zlib.lib(zlib1.dll)
zlib.lib(inflate.obj) : error LNK2005: inflateInit2_ already defined in zlib.lib(zlib1.dll)
zlib.lib(deflate.obj) : error LNK2005: deflate already defined in zlib.lib(zlib1.dll)
zlib.lib(deflate.obj) : error LNK2005: deflateBound already defined in zlib.lib(zlib1.dll)
zlib.lib(deflate.obj) : error LNK2005: deflateEnd already defined in zlib.lib(zlib1.dll)
zlib.lib(deflate.obj) : error LNK2005: deflateInit2_ already defined in zlib.lib(zlib1.dll)
   Creating library ..\..\bin\eepp-empty-window.lib and object ..\..\bin\eepp-empty-window.exp
..\..\bin\eepp-empty-window.exe : fatal error LNK1169: one or more multiply defined symbols found
Done building project "eepp-empty-window.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 28 up-to-date, 0 skipped ==========```

**Comment by SpartanJ** [comment]
Mmhh probably the static compilation isn't working, I haven't statically compiled eepp in a long time, let me check it out. Meanwhile, you can disable the `--with-static-eepp` flag.

**Comment by sornian** [comment]
I try to clone new version and compile static，but it has same result....

And I have a question ,why download  SDL2 instead of compile it by source code...(the download of sdl2 is dll not static lib)

And I provide a suggestion :add compile command line "/utf-8" in msvc。because in many country windows os char-set is ascii not uft-8  It will cause some error

**Comment by SpartanJ** [comment]
> I try to clone new version and compile static，but it has same result....

Thanks for letting me know, I'll check it again. It must be something trivial that I'm missing.

> And I have a question ,why download SDL2 instead of compile it by source code...(the download of sdl2 is dll not static lib)

Simply for convenience, it's simpler, but you can statically build with static SDL2 using the premake option:

```
 --with-static-backend      It will try to compile the library with a static backend (only for gcc and mingw).
                                The backend should be placed in libs/your_platform/libYourBackend.a
```

> And I provide a suggestion :add compile command line "/utf-8" in msvc。because in many country windows os char-set is ascii not uft-8 It will cause some error

Since I never had a problem I didn't know about that flag, I'm not an MSVC user. I'll add that flag. Thanks for letting me know.
