### ISSUE TITLE
MacOS SDL2 Build Linking

### ISSUE THREAD

**Issue by TerminalFi** [SpartanJ/eepp#17]
On MacOS (`13.2.1 (22D68)`) I've noticed that installing SDL2 via homebrew `brew install sdl2` results in a different Lib path than expected and is not linked to the expected `/Library/Frameworks/SDL2.framework/` folder

As you can see below 

```
sdl2-config --cflags --libs
-I/opt/homebrew/include/SDL2 -D_THREAD_SAFE
-L/opt/homebrew/lib -lSDL2
```

These are the locations of the libs once installed with Homebrew. Either a Troubleshooting step for users to do a `ln -s` needs to happen or within the `premake2` configs it needs to account for additional SDL2 locations on MacOS

**Comment by SpartanJ** [comment]
There's a flag in the premake file for the usage of frameworks, the flag is called `--use-frameworks`. What I need to fix is the ecode's `build.app.sh` build script, that it's currently forcing the build without frameworks (brew installed SDL2) and hardcoding the `libSDL2-2.0.0.dylib` path. I think I will change the build script to use the SDL2 framework package, since that's how it's officially distributed.

**Comment by SpartanJ** [comment]
Sorry if I wasn't clear. We shouldn't use the libSDL2 install from brew, but the official package provided [here](https://github.com/libsdl-org/SDL/releases/latest). But you're right, if we don't use frameworks I should run `sdl2-config --cflags --libs` to get the correct flags and lib path, I'll fix it.

**Comment by TerminalFi** [comment]
Ahh I understand.

**Comment by SpartanJ** [comment]
The official package uses a different path nomenclature, it does not use the `SDL2/` path. I always hate it! But that's a bug with my patched `mojoal`. If you go to that file, line 63, it's not checking correctly where to find `SDL.h`. Give me some minutes and I'll push a fix, meanwhile, you can simply fix the path where I mention it.

**Comment by TerminalFi** [comment]
Premake5


https://user-images.githubusercontent.com/32599364/229204929-45879082-52dd-4292-9ec7-05214fa44357.mp4

**Comment by TerminalFi** [comment]
For now, yes I am just modifying files after running premake5 to get builds working. But wanted to surface that for some reason it is not working properly on M1 mac

**Comment by SpartanJ** [comment]
I pushed a fix that should work. I also added support to build ecode with frameworks and added a cross-build script to build from x86_64 the arm64 ecode but I don't have a way to test the build in an arm64 mac, can you do me the favor of testing the macOS build, please?
[ecode-macos-0.4.8-arm64.zip](https://github.com/SpartanJ/eepp/files/11127799/ecode-macos-0.4.8-arm64.zip)

**Comment by TerminalFi** [comment]
Sure let me check it out

**Comment by TerminalFi** [comment]
Looks like there was some issues

```
dyld[8997]: Library not loaded: @rpath/libeepp.dylib
  Referenced from: <CD1E142A-F2A3-3AC0-98C7-DB92B4DEB949> /Applications/ecode.app/Contents/MacOS/ecode
  Reason: tried: '/Applications/ecode.app/Contents/MacOS/../libs/macosx/libeepp.dylib' (no such file), '$ORIGIN/libeepp.dylib' (no such file), '/Applications/ecode.app/Contents/MacOS/../libs/macosx/libeepp.dylib' (no such file), '$ORIGIN/libeepp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS@rpath/libeepp.dylib' (no such file), '/Applications/ecode.app/Contents/MacOS/../libs/macosx/libeepp.dylib' (no such file), '$ORIGIN/libeepp.dylib' (no such file), '/Applications/ecode.app/Contents/MacOS/../libs/macosx/libeepp.dylib' (no such file), '$ORIGIN/libeepp.dylib' (no such file), '/usr/local/lib/libeepp.dylib' (no such file), '/usr/lib/libeepp.dylib' (no such file, not in dyld cache)
./run.sh: line 3:  8997 Abort trap: 6           ./ecode $@
```

**Comment by SpartanJ** [comment]
I messed up the library path. I think [this build](https://github.com/SpartanJ/eepp/files/11127973/ecode-macos-0.4.8-arm64.zip) should fix the issue. Can you try again, please?

**Comment by TerminalFi** [comment]
Build works great!

**Comment by SpartanJ** [comment]
Great! I'll add it to the release packages. Thanks for helping me!

**Comment by SpartanJ** [comment]
I'll close the issue since it has already been fixed this weekend.
