### ISSUE TITLE
Build instructions for MSYS2 MINGW64

### ISSUE THREAD

**Issue by iahung** [SpartanJ/eepp#21]
Instructions for standalone MinGW doesn't work. On MSYS2, there is only premake5: `mingw-w64-x86_64-premake`.

**Comment by SpartanJ** [comment]
May be [this](https://github.com/SpartanJ/eepp/issues/19) might help you?
It seems that I need to make a couple of changes to support MSYS2 builds.

**Comment by SpartanJ** [comment]
I'll close this issue, if instructions say to use premake5, you just need to download premake5. But the mingw distributed premake should work, since eepp supports premake4 and 5, so it doesn't matter which version is being distributed.

**Comment by iahung** [comment]
> Maybe [this](https://github.com/SpartanJ/eepp/issues/19) might help you? It seems that I need to make a couple of changes to support MSYS2 builds.

It seems only `premake5 gmake` is needed, it's building now.

**Comment by iahung** [comment]
It doesn't find openal even though openal is installed mingw-w64-x86_64-openal 1.23.0-1 [installed]

```
Linking eepp-shared
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lOpenAL32: No such file or directory
collect2.exe: error: ld returned 1 exit status
make[1]: *** [eepp-shared.make:529: ../../libs/windows/x86_64/eepp-debug.dll] Error 1
make: *** [Makefile:387: eepp-shared] Error 2
make: Leaving directory '/home/Administrator/eepp/make/windows'
```

**Comment by iahung** [comment]
> MSYS does not provide that package (only openal-soft).

So what is `mingw-w64-x86_64-openal`? This package was installed and SuperTux could see it and use it. OpenAL is also a dependency of SuperTux.

**Comment by SpartanJ** [comment]
Yes, it's openal-soft, but the library is not named OpenAL32 for some reason, that's why it does not find it. I think that for MSYS2 is should link against "openal". I might add some fixes for MSYS2 in the project configuration, but it's hard to keep support for everything.
