### ISSUE TITLE
Syntax definition improvement

### ISSUE THREAD

**Issue by iahung3** [SpartanJ/eepp#36]
> I've been taking a look at the FreeBASIC documentation and they seem to use mostly camel-case on all example, I think we will need to support as base the camel-case version, plus lowercase and uppercase which are the most common cases. If you add camel-case then adding the rest is trivial because ecode lets you uppercase and lowercase a range of text with ctrl + alt + shift + Up or Down (to upper or lowercase). So you can create the camel-case block, and copy paste the block, uppercase it, copy paste and lowercase it.

It's better if you could add something like `.setCaseInsensitive( true );`. Only a handful of languages are case insensitive, so this will not affect the performance.

_Originally posted by @iahung3 in https://github.com/SpartanJ/eepp/issues/35#issuecomment-2018368331_

**Comment by SpartanJ** [comment]
Ok, I agree, I'll do it.

**Comment by SpartanJ** [comment]
Implemented!
