### ISSUE TITLE
A textbox doesn't get focus when the text in it is selected?

### ISSUE THREAD

**Issue by iahung3** [SpartanJ/eepp#43]
Selecting text in a textbox doesn't mean you are editing it? What is the logic behind that?

It's annoying. I select the text and start typing. I expect what I type to replace the selected text. Then I quickly realized that I'm typing into nowhere and the text I'm selecting is still there!

Note: This is about all of the textboxes in the UI, not the editor area!

**Comment by SpartanJ** [comment]
Transferred the issue because this is an eepp GUI issue.

**Comment by iahung3** [comment]
> I pushed an small fix and seems to work fine, I'll be testing these days, please if you want to help me testing I'll appreciate it.

I don't see any problems.

**Comment by SpartanJ** [comment]
I consider this issue done, if I found any other related issue I'll fix it but keep this new behaviour.
