### ISSUE TITLE
Please add Meson build script

### ISSUE THREAD

**Issue by Curculigo** [SpartanJ/eepp#51]
This project could be used as the reference:

https://github.com/franko/fox

**Comment by SpartanJ** [comment]
We already discussed the topic in issue #33 . I haven't changed my mind.

**Comment by Curculigo** [comment]
> We already discussed the topic in issue #33 . I haven't changed my mind.

Not CMake. Not Meson. Then what? The Chinese's XMake?

**Comment by SpartanJ** [comment]
There's no need for any change... Whatever I like better. I'm OK with premake for now.
