### ISSUE TITLE
Improve Build Documentation (especially for, e.g., Haiku OS)

### ISSUE THREAD

**Issue by b4ux1t3** [SpartanJ/eepp#52]
I'm currently struggling through the process of building ecode, and I think there's room for some better docs (maybe broken out from the README?).

To be clear, I'm not asking for help building, just establishing an issue with the current documentation.

I'd be happy to write up a PR as a result of my efforts. . .you know, once I manage to get it built!

I'm also very aware that you're in the process (or soon will be) of moving ecode over to the new repo, so if you'd prefer I can target that repo with any documentation updates I come up with.

**Comment by b4ux1t3** [comment]
I. . .did not find that script, I've been doing it manually 😅 

FWIW I've gotten to the point where it needs to include SOIL2, and it's erroring out there (which is is odd, because I found, built and added it to my non-packaged/lib directory).

I just ran the script, and it ended up erroring in the same place: 

![image-of-error](https://github.com/user-attachments/assets/30bdf377-7add-4388-a731-5487c70364df)

I'm wondering if I need to roll back some of the stuff I've done and use that script from a clean system. I'll give that a try. 

Thanks!

**Comment by SpartanJ** [comment]
You did not [pull the submodules](https://github.com/SpartanJ/eepp/?tab=readme-ov-file#getting-the-code) :).

do a: `git pull --recurse-submodules`.

**Comment by SpartanJ** [comment]
FYI: Haiku version isn't much stable currently since I don't have a native installation on my HW and OpenGL context has many problems while running on a VM (at least for me, not sure why, but the OS completely freezes).

**Comment by b4ux1t3** [comment]
🤦 Ha! My git is aliased in my zshrc to automatically get submodules.

I forgot that was a thing I needed to do since I didn't bring my zshrc to haiku!

**Comment by SpartanJ** [comment]
[Added](https://github.com/SpartanJ/ecode?tab=readme-ov-file#build-from-source) build information for Haiku and FreeBSD.
