### ISSUE TITLE
Do you really test your build instructions on Windows?

### ISSUE THREAD

**Issue by chatchoi** [SpartanJ/eepp#54]
https://github.com/SpartanJ/eepp?tab=readme-ov-file#mingw

First, `make\windows` will not work in w64devkit because it will treat `\` as the escape character, so it will see `make\windows` as `makewindows`. No such file or directory. The correct is `make/windows`.

But even that, the build process will fail with:

```
Linking eepp-shared
Running postbuild commands
ln -sf "C:/Build/eepp/libs/windows/x86_64/eepp-debug.dll" "C:/Build/eepp/bin/"
ln: C:/Build/eepp/bin/eepp-debug.dll: Permission denied
make[1]: *** [eepp-shared.make:1000: ../../libs/windows/x86_64/eepp-debug.dll] Error 1
make: *** [Makefile:450: eepp-shared] Error 2
make: Leaving directory 'C:/Build/eepp/make/windows'
```

**Comment by SpartanJ** [comment]
`ln: C:/Build/eepp/bin/eepp-debug.dll: Permission denied`
Did you run as an administrator? That looks like your problem.

Yes, I did test it some time ago, I simply made a typo there. If something looks wrong and you know how to fix it you can send a PR to fix the documentation instead of using passive-aggressive questions. This is an open-source project with a single maintainer, I do what I can and want. BTW, I just did a build from zero and works by just fixing that typo. You need to run the terminal as administrator, that's it.

**Comment by chatchoi** [comment]
You don't run untrusted program as administrator. Modify your build script to use copy instead of symlink. This is the way to do.

**Comment by SpartanJ** [comment]
Feel free to collaborate with the improvement.

**Comment by chatchoi** [comment]
w64devkit is optimized for small binary size. It's terrible for either performance or debug. MSYS2 is still the better way. This is what I want to tell you. I know you hate me and I don't bother you any further. Keep this Lua patterns and no one will use your text editor. Lua people will use text editor written in Lua, not a big C++ mess. Goodbye.

**Comment by SpartanJ** [comment]
> w64devkit is optimized for small binary size. It's terrible for either performance or debug. MSYS2 is still the better way. This is what I want to tell you.

But I don't distribute any build made from w64devkit, you can just collaborate expanding the documentation to build it with msys2, it's possible to build it with any tool-chain, I just used the simpler one. ecode is cross built with mingw64 from Linux.

> I know you hate me and I don't bother you any further. Keep this Lua patterns and no one will use your text editor. Lua people will use text editor written in Lua, not a big C++ mess. Goodbye.

I don't hate you, you're just *very rude*, you need to learn some manners, that's all (and stop creating different alt accounts, it's very confusing).

> Keep this Lua patterns and no one will use your text editor. Lua people will use text editor written in Lua, not a big C++ mess.

I already told you that I'll add support in the near future, man, give me a break.

**Comment by chatchoi** [comment]
Alt account what? This is my only account up to now.
