### ISSUE TITLE
Stuck at SOIL2

### ISSUE THREAD

**Issue by Curculigo** [SpartanJ/eepp#55]
I have problem with LLVM 19.0.1. So instead of just downgrading to LLVM 18.1.8, I decided to test other MinGW-w64 distros. I have tested niXman and winlibs.com. All of them stuck at SOIL2. This is the error message:

```
==== Building SOIL2-static (release_x86_64) ====
SOIL2.c
../../src/thirdparty/SOIL2/src/SOIL2/SOIL2.c: In function ‘get_glCompressedTexImage2D_addr’:
../../src/thirdparty/SOIL2/src/SOIL2/SOIL2.c:3191:56: error: ‘glCompressedTexImage2D’ undeclared (first use in this function); did you mean ‘s’?
 3191 |         ext_addr = (P_SOIL_GLCOMPRESSEDTEXIMAGE2DPROC)&glCompressedTexImage2D;
      |                                                        ^~~~~~~~~~~~~~~~~~~~~~
      |                                                        soilGlCompressedTexImage2D
../../src/thirdparty/SOIL2/src/SOIL2/SOIL2.c:3191:56: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [SOIL2-static.make:175: ../../obj/windows/x86_64/release/SOIL2-static/SOIL2.o] Error 1
make: *** [Makefile:324: SOIL2-static] Error 2
make: Leaving directory '/c/foo/eepp/make/windows'
```

This is very interesting. I checked `SOIL2-static.make` generated by premake5. Nothing strange here. I don't think there is anything in the environment could affect the evaluation of the `SOIL_PLATFORM_WIN32` macro and I indeed built a small test program to confirm that the check like on line 69 of SOIL2.c really works:

```
#if defined( __WIN32__ ) || defined( _WIN32 ) || defined( WIN32 )
```

(Note: this check worked, and `SOIL_PLATFORM_WIN32` should be defined).

But the error is at line 3191 of SOIL2.c. Please have a look at the code snippet:

```
#if defined( SOIL_PLATFORM_WIN32 ) || defined( SOIL_PLATFORM_OSX ) || defined( SOIL_X11_PLATFORM )
	ext_addr = (P_SOIL_GLCOMPRESSEDTEXIMAGE2DPROC)SOIL_GL_GetProcAddress( "glCompressedTexImage2D" );
#else
	ext_addr = (P_SOIL_GLCOMPRESSEDTEXIMAGE2DPROC)&glCompressedTexImage2D; // this is line 3191
#endif
```

This means `SOIL_PLATFORM_WIN32` is not defined, or this check failed:

```
#if defined( SOIL_PLATFORM_WIN32 ) || defined( SOIL_PLATFORM_OSX ) || defined( SOIL_X11_PLATFORM )
```

I have no idea what's going on.

**Comment by Curculigo** [comment]
The environment is MSYS2. The shell is MSYS2 MSYS, with the Cygwin GCC installed, but I have used the `PATH` trick to have the MinGW-w64 GCC preferred. `gcc -v` confirms that it's the MinGW-w64 GCC, not the Cygwin GCC. The make implementation used is GNU Make (POSIX), not mingw32-make, because mingw32-make will have problems processing the paths on MSYS2 MSYS.

The very same setup worked with llvm-mingw.

**Comment by Curculigo** [comment]
I found the problem. The makefile generated by premake5 is somehow still calling `cc` for C compiler instead of `gcc`. MinGW-w64 distros like niXman and winlibs.com don't include `cc.exe`. `/usr/bin/cc` which is the Cygwin GCC will be called instead. llvm-mingw includes a `cc.exe` so everything is working out of the box. The same is also true for w64devkit.

**Comment by SpartanJ** [comment]
Yes, you can override the default compiler with environment flags, CC and you'll need CXX for C++. Mixing environments will lead you to unpredictable results and extremely confusing situations.
