### ISSUE TITLE
make fails in pop_os 22.04

### ISSUE THREAD

**Issue by anythingwithawire** [SpartanJ/eepp#6]
followed instructions, used premake4, aborts make with

...
alcheck.cpp
In file included from ../../src/eepp/audio/alcheck.cpp:1:
../../src/eepp/audio/alcheck.hpp:10:10: fatal error: AL/al.h: No such file or directory
   10 | #include <AL/al.h>
      |          ^~~~~~~~~
compilation terminated.
make[1]: *** [eepp-shared.make:612: ../../obj/linux/debug/eepp-shared/alcheck.o] Error 1
make: *** [Makefile:93: eepp-shared] Error 2

modified alcheck.hpp to point to full path of file locations, but then further similar errors I tried workign thru but then just gave up.

**Comment by SpartanJ** [comment]
You used `premake4 --with-mojoal gmake`?
It's complaining that it couldn't find OpenAL header files, it should be including it automatically if used with mojoal, otherwise you'll need to install openal-soft-devel package. I don't know how it's called in pop OS.
If didn't work even using `--with-mojoal` then it's a minor bug.

The readme states:
`Notice: OpenAL is not strictly necessary. If you want to avoid it, you have the alternative to use [mojoAL](https://icculus.org/mojoAL/). The latter is already integrated to the library but not enabled by default. To enable it and disable the OpenAL dependency you need to add the parameter --with-mojoal to any premake call ( ex: premake5 --with-mojoal gmake2 ).`

Let me know if that was the issue.

**Comment by anythingwithawire** [comment]
yeah i tried with and without the mojal option, i am up to maybe 5 times
and now I have another but looks like related problem.

mostly it seems the files are there, but the working directory is incorrect
for the path

eg in alcheck.hpp

#ifndef EE_ALCHECK_HPP
#define EE_ALCHECK_HPP

#include <eepp/config.hpp>

#ifdef EE_USE_FRAMEWORKS
#include <OpenAL/al.h>
#include <OpenAL/alc.h>
#else
#include <../../AL/al.h>
#include <../../AL/alc.h>

**Comment by SpartanJ** [comment]
Send me the whole output please, it should be something trivial, try building with:
```bash
premake4 --with-mojoal gmake
cd make/linux
make config=release verbose=true
```
As another option you can use the ecode build script located at:
```bash
cd projects/linux/ecode
./build.app.sh
```
I'm always assuming that your starting directory is the root directory of eepp.

**Comment by anythingwithawire** [comment]
On Tue, Jan 17, 2023 at 12:44 AM Martín Lucas Golini <
***@***.***> wrote:

i have butchered it, i will need to download again, see how i go it is
12:47am here

**Comment by anythingwithawire** [comment]
***@***.***:~/eepp$ git clone --recurse-submodules
https://github.com/SpartanJ/eepp.git
Cloning into 'eepp'...
remote: Enumerating objects: 58540, done.
remote: Counting objects: 100% (9309/9309), done.
remote: Compressing objects: 100% (2111/2111), done.
remote: Total 58540 (delta 6849), reused 9124 (delta 6699), pack-reused
49231
Receiving objects: 100% (58540/58540), 67.88 MiB | 3.26 MiB/s, done.
Resolving deltas: 100% (33600/33600), done.
Submodule 'src/thirdparty/SOIL2' (https://github.com/SpartanJ/soil2)
registered for path 'src/thirdparty/SOIL2'
Submodule 'src/thirdparty/efsw' (https://github.com/SpartanJ/efsw)
registered for path 'src/thirdparty/efsw'
Cloning into '/home/gareth/eepp/eepp/src/thirdparty/SOIL2'...
remote: Enumerating objects: 735, done.
remote: Counting objects: 100% (204/204), done.
remote: Compressing objects: 100% (110/110), done.
remote: Total 735 (delta 98), reused 166 (delta 76), pack-reused 531
Receiving objects: 100% (735/735), 1.56 MiB | 2.79 MiB/s, done.
Resolving deltas: 100% (249/249), done.
Cloning into '/home/gareth/eepp/eepp/src/thirdparty/efsw'...
remote: Enumerating objects: 2224, done.
remote: Counting objects: 100% (383/383), done.
remote: Compressing objects: 100% (241/241), done.
remote: Total 2224 (delta 176), reused 280 (delta 136), pack-reused 1841

Receiving objects: 100% (2224/2224), 937.24 KiB | 1.16 MiB/s, done.
Resolving deltas: 100% (880/880), done.
Submodule path 'src/thirdparty/SOIL2': checked out
'957d538a5561f029a0760914979426693edc4c7e'
Submodule path 'src/thirdparty/efsw': checked out
'8af1ebfe2d4ba0aff30a2c3ad99b56051a2aa3ee'
***@***.***:~/eepp$ premake4  gmake
Selected SDL2
Using SDL2 backend
Selected SDL2
Using SDL2 backend
Building configurations...
Running action 'gmake'...
Generating make/linux/Makefile...
Generating make/linux/SOIL2-static.make...
Generating make/linux/glew-static.make...
Generating make/linux/mbedtls-static.make...
Generating make/linux/vorbis-static.make...
Generating make/linux/pugixml-static.make...
Generating make/linux/zlib-static.make...
Generating make/linux/libzip-static.make...
Generating make/linux/libpng-static.make...
Generating make/linux/freetype-static.make...
Generating make/linux/chipmunk-static.make...
Generating make/linux/jpeg-compressor-static.make...
Generating make/linux/imageresampler-static.make...
Generating make/linux/efsw-static.make...
Generating make/linux/eepp-maps-static.make...
Generating make/linux/eepp-maps.make...
Generating make/linux/eepp-physics-static.make...
Generating make/linux/eepp-physics.make...
Generating make/linux/eterm-static.make...
Generating make/linux/eepp-static.make...
Generating make/linux/eepp-shared.make...
Generating make/linux/eepp-external-shader.make...
Generating make/linux/eepp-empty-window.make...
Generating make/linux/eepp-sound.make...
Generating make/linux/eepp-sprites.make...
Generating make/linux/eepp-fonts.make...
Generating make/linux/eepp-vbo-fbo-batch.make...
Generating make/linux/eepp-physics-demo.make...
Generating make/linux/eepp-http-request.make...
Generating make/linux/eepp-ui-hello-world.make...
Generating make/linux/eepp-textureatlaseditor.make...
Generating make/linux/eepp-mapeditor.make...
Generating make/linux/eepp-uieditor.make...
Generating make/linux/ecode.make...
Generating make/linux/eterm.make...
Generating make/linux/eepp-texturepacker.make...
Generating make/linux/eepp-test.make...
Generating make/linux/eepp-ui-perf-test.make...
Done.
***@***.***:~/eepp$ make -C make/linux
make: Entering directory '/home/gareth/eepp/make/linux'
==== Building SOIL2-static (debug) ====
==== Building glew-static (debug) ====
==== Building mbedtls-static (debug) ====
==== Building vorbis-static (debug) ====
==== Building pugixml-static (debug) ====
==== Building zlib-static (debug) ====
==== Building libzip-static (debug) ====
==== Building libpng-static (debug) ====
==== Building freetype-static (debug) ====
==== Building chipmunk-static (debug) ====
==== Building jpeg-compressor-static (debug) ====
==== Building imageresampler-static (debug) ====
==== Building efsw-static (debug) ====
==== Building eepp-maps-static (debug) ====
==== Building eepp-shared (debug) ====
wminfo.cpp
../../src/eepp/window/backend/SDL2/wminfo.cpp: In member function
‘EE::Window::X11Window EE::Window::Backend::SDL2::WMInfo::getWindow()’:
../../src/eepp/window/backend/SDL2/wminfo.cpp:39:16: error: invalid
conversion from ‘SDL_SysWMinfo*’ to ‘EE::Window::X11Window’ {aka ‘long
unsigned int’} [-fpermissive]
   39 |         return info;
      |                ^~~~
      |                |
      |                SDL_SysWMinfo*
../../src/eepp/window/backend/SDL2/wminfo.cpp: In member function
‘_XDisplay* EE::Window::Backend::SDL2::WMInfo::getWindowHandler()’:
../../src/eepp/window/backend/SDL2/wminfo.cpp:52:16: error: cannot convert
‘SDL_SysWMinfo*’ to ‘EE::Window::eeWindowHandle’ {aka ‘_XDisplay*’} in
return
   52 |         return info;
      |                ^~~~
make[1]: *** [eepp-shared.make:1410:
../../obj/linux/debug/eepp-shared/wminfo.o] Error 1
make: *** [Makefile:93: eepp-shared] Error 2
make: Leaving directory '/home/gareth/eepp/make/linux'
***@***.***:~/eepp$ premake4 --with-mojoal gmake
Selected SDL2
Using SDL2 backend
Selected SDL2
Using SDL2 backend
Building configurations...
Running action 'gmake'...
Generating make/linux/Makefile...
Generating make/linux/SOIL2-static.make...
Generating make/linux/glew-static.make...
Generating make/linux/mbedtls-static.make...
Generating make/linux/vorbis-static.make...
Generating make/linux/pugixml-static.make...
Generating make/linux/zlib-static.make...
Generating make/linux/libzip-static.make...
Generating make/linux/libpng-static.make...
Generating make/linux/freetype-static.make...
Generating make/linux/chipmunk-static.make...
Generating make/linux/jpeg-compressor-static.make...
Generating make/linux/imageresampler-static.make...
Generating make/linux/mojoal-static.make...
Generating make/linux/efsw-static.make...
Generating make/linux/eepp-maps-static.make...
Generating make/linux/eepp-maps.make...
Generating make/linux/eepp-physics-static.make...
Generating make/linux/eepp-physics.make...
Generating make/linux/eterm-static.make...
Generating make/linux/eepp-static.make...
Generating make/linux/eepp-shared.make...
Generating make/linux/eepp-external-shader.make...
Generating make/linux/eepp-empty-window.make...
Generating make/linux/eepp-sound.make...
Generating make/linux/eepp-sprites.make...
Generating make/linux/eepp-fonts.make...
Generating make/linux/eepp-vbo-fbo-batch.make...
Generating make/linux/eepp-physics-demo.make...
Generating make/linux/eepp-http-request.make...
Generating make/linux/eepp-ui-hello-world.make...
Generating make/linux/eepp-textureatlaseditor.make...
Generating make/linux/eepp-mapeditor.make...
Generating make/linux/eepp-uieditor.make...
Generating make/linux/ecode.make...
Generating make/linux/eterm.make...
Generating make/linux/eepp-texturepacker.make...
Generating make/linux/eepp-test.make...
Generating make/linux/eepp-ui-perf-test.make...
Done.
***@***.***:~/eepp$ make -C make/linux
make: Entering directory '/home/gareth/eepp/make/linux'
==== Building SOIL2-static (debug) ====
==== Building glew-static (debug) ====
==== Building mbedtls-static (debug) ====
==== Building vorbis-static (debug) ====
==== Building pugixml-static (debug) ====
==== Building zlib-static (debug) ====
==== Building libzip-static (debug) ====
==== Building libpng-static (debug) ====
==== Building freetype-static (debug) ====
==== Building chipmunk-static (debug) ====
==== Building jpeg-compressor-static (debug) ====
==== Building imageresampler-static (debug) ====
==== Building mojoal-static (debug) ====
==== Building efsw-static (debug) ====
==== Building eepp-maps-static (debug) ====
==== Building eepp-shared (debug) ====
wminfo.cpp
../../src/eepp/window/backend/SDL2/wminfo.cpp: In member function
‘EE::Window::X11Window EE::Window::Backend::SDL2::WMInfo::getWindow()’:
../../src/eepp/window/backend/SDL2/wminfo.cpp:39:16: error: invalid
conversion from ‘SDL_SysWMinfo*’ to ‘EE::Window::X11Window’ {aka ‘long
unsigned int’} [-fpermissive]
   39 |         return info;
      |                ^~~~
      |                |
      |                SDL_SysWMinfo*
../../src/eepp/window/backend/SDL2/wminfo.cpp: In member function
‘_XDisplay* EE::Window::Backend::SDL2::WMInfo::getWindowHandler()’:
../../src/eepp/window/backend/SDL2/wminfo.cpp:52:16: error: cannot convert
‘SDL_SysWMinfo*’ to ‘EE::Window::eeWindowHandle’ {aka ‘_XDisplay*’} in
return
   52 |         return info;
      |                ^~~~
make[1]: *** [eepp-shared.make:1410:
../../obj/linux/debug/eepp-shared/wminfo.o] Error 1
make: *** [Makefile:97: eepp-shared] Error 2
make: Leaving directory '/home/gareth/eepp/make/linux'
***@***.***:~/eepp$

**Comment by SpartanJ** [comment]
That's weird. Well, I was curious and installed a popOS 22.04 in a VM.
I did the following:
```bash
sudo apt install libsdl2-dev premake4 g++
git clone --recurse-submodules https://github.com/SpartanJ/eepp.git
cd eepp
premake4 --with-mojoal
make -j$(nproc) -C make/linux
```
And... it worked just fine... so I'm puzzled. I don't know what to say.

**Comment by anythingwithawire** [comment]
ok so i pasted in your commands, first go (starting from home directory)

***@***.***:~$ sudo apt install libsdl2-dev premake4 g++
git clone --recurse-submodules https://github.com/SpartanJ/eepp.git
cd eepp
premake4 --with-mojoal
make -j$(nproc) -C make/linux
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
g++ is already the newest version (4:11.2.0-1ubuntu1).
premake4 is already the newest version (4.3+repack1-2build1).
libsdl2-dev is already the newest version (2.0.20+dfsg-2ubuntu1.22.04.1).
0 to upgrade, 0 to newly install, 0 to remove and 57 not to upgrade.
Cloning into 'eepp'...
remote: Enumerating objects: 58540, done.
remote: Counting objects: 100% (9309/9309), done.
remote: Compressing objects: 100% (2111/2111), done.
remote: Total 58540 (delta 6849), reused 9124 (delta 6699), pack-reused
49231
Receiving objects: 100% (58540/58540), 67.88 MiB | 2.64 MiB/s, done.
Resolving deltas: 100% (33600/33600), done.
Submodule 'src/thirdparty/SOIL2' (https://github.com/SpartanJ/soil2)
registered for path 'src/thirdparty/SOIL2'
Submodule 'src/thirdparty/efsw' (https://github.com/SpartanJ/efsw)
registered for path 'src/thirdparty/efsw'
Cloning into '/home/gareth/eepp/src/thirdparty/SOIL2'...
remote: Enumerating objects: 735, done.
remote: Counting objects: 100% (204/204), done.
remote: Compressing objects: 100% (110/110), done.
remote: Total 735 (delta 98), reused 166 (delta 76), pack-reused 531
Receiving objects: 100% (735/735), 1.56 MiB | 2.09 MiB/s, done.
Resolving deltas: 100% (249/249), done.
Cloning into '/home/gareth/eepp/src/thirdparty/efsw'...
remote: Enumerating objects: 2224, done.
remote: Counting objects: 100% (383/383), done.
remote: Compressing objects: 100% (241/241), done.
remote: Total 2224 (delta 176), reused 280 (delta 136), pack-reused 1841

Receiving objects: 100% (2224/2224), 937.24 KiB | 1.42 MiB/s, done.
Resolving deltas: 100% (880/880), done.
Submodule path 'src/thirdparty/SOIL2': checked out
'957d538a5561f029a0760914979426693edc4c7e'
Submodule path 'src/thirdparty/efsw': checked out
'8af1ebfe2d4ba0aff30a2c3ad99b56051a2aa3ee'
Selected SDL2
Using SDL2 backend
Selected SDL2
Using SDL2 backend
Type 'premake4 --help' for help
make: *** make/linux: No such file or directory.  Stop.
***@***.***:~/eepp$

**Comment by anythingwithawire** [comment]
however if i do

premake4 --with-mojoal gmake

make -j$(nproc) -C make/linux


it seems to build, haven't tested yet

**Comment by SpartanJ** [comment]
haha sorry, forgot the `gmake`

**Comment by anythingwithawire** [comment]
though if i try to run the ecode AppRun it makes a brief flicker on the
file manager, but nothing starts, ecode ran when I downloaded the package
previously

**Comment by anythingwithawire** [comment]
ok thx, i gotta go to bed, need to work tomorrow

**Comment by SpartanJ** [comment]
No problem, to run ecode should be:

```bash
cd bin
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../libs/linux/ ./ecode-debug
```

AppRun is for the AppImage. You build a debug version, It closed because it didn't find the assets.

**Comment by SpartanJ** [comment]
The build seems to work fine, I need to improve how to access the demo after the build.
