### ISSUE TITLE
How to cross compile from Linux to Windows?

### ISSUE THREAD

**Issue by chatchoi** [SpartanJ/eepp#69]
If it's already on README.md then I'm sorry, too long so I don't read. Please point me to exactly which section covering this.

**Comment by Curculigo** [comment]
README.md doesn't cover this. But this script is self-explanatory:

https://github.com/SpartanJ/eepp/blob/develop/projects/mingw32/ecode/build.app.sh

**Comment by SpartanJ** [comment]
You can copy step by step what the nightly builds CI is doing: [here](https://github.com/SpartanJ/eepp/blob/develop/.github/workflows/ecode-nightly.yml#L150C17-L150C22), although it does many unnecessary things.
It's basically install mingw64, run the script.
