### ISSUE TITLE
Installing into the file system on Linux

### ISSUE THREAD

**Issue by chatchoi** [SpartanJ/eepp#70]
OK. Your premake build scripts, either 4 or 5, don't offer any install scripts, so make install will not work. The location of `assets` is fixed, needs to be patched in source code (https://github.com/SpartanJ/ecode/discussions/243 https://github.com/SpartanJ/ecode/discussions/280), so another reason for Linux distributions to ignore packaging your software officially. I mean DEB or RPM or something like that. AppImage is only a workaround since your software can never be part of the official packages provided by the distributions.

**Comment by Curculigo** [comment]
At least on Ubuntu/Debian, I know `/usr/lib` could be used. The JVM is installed in `/usr/lib/jvm`. LLVM is installed in `/usr/lib/llvm-[version]`. So ecode should be installed in `/usr/lib/ecode`. And `/opt` is always available (`/opt/ecode`). If someone is crafting their own install script, they could consider `/usr/local` (`/usr/local/ecode`), too. None of the above needs the source code to be patched to move the location of the `assets` directory.

**Comment by SpartanJ** [comment]
Changing the assets path is a single line patch, it's done purposefully because of this. I  have collaborated in apps packaging for some distributions and this is the way they always do it, they just patch the paths, so it's not a problem.
