### ISSUE TITLE
premake4 build script is broken on FreeBSD

### ISSUE THREAD

**Issue by Curculigo** [SpartanJ/eepp#71]
The premake5 build script is working fine, so this bug report is only to inform the developer that such a bug exists.

There are no gcc or g++ in a default FreeBSD system, but there are cc and c++ binaries. The premake5 build script has no problem picking the correct compilers. The premake4 build script will try to pick gcc and g++ by default and of course it will fail because these don't exist. I have to force it to use the correct compiler by CC=cc CXX=c++ but it still fails at SOIL2 because it can't find GL/gl.h.

**Comment by Curculigo** [comment]
Just use premake5 whenever it's possible. I know this would be the answer and I accept it.

**Comment by SpartanJ** [comment]
I would fix it but this is an error in premake4 implementation that uses the CC and CXX vars with GCC. this is easily fixed by just overriding the environment variable of CC and CXX with clang and clang++ respectively.

> I have to force it to use the correct compiler by CC=cc CXX=c++ but it still fails at SOIL2 because it can't find GL/gl.h.

This sound unrelated btw.
