### ISSUE TITLE
OpenGL 4

### ISSUE THREAD

**Issue by chadchoi** [SpartanJ/eepp#76]
OpenGL 4 is not mentioned in the supported list.

> - Renderers for OpenGL 2 ( fixed-pipeline ), OpenGL 3 ( programmable-pipeline ), OpenGL ES 2, OpenGL ES 1, and OpenGL Core Profile.

No support for modern OpenGL?

I only asked because I'm curious. I don't know anything about OpenGL and computer graphics. OpenGL seems to be [a mess](https://www.phoronix.com/forums/forum/software/linux-gaming/1498317-unvanquished-working-on-opengl-4-6-renderer-support?p=1498385#post1498385).

**Comment by SpartanJ** [comment]
OpenGL 3 Core Profile for eepp use case is basically OpenGL 4 ("modern OpenGL", I could theoretically start the context as OpenGL 4 but it does not bring any particular benefit for an 2D app, but, it can limit the GPU support for no benefit. Anyway in 2024 is kinda guaranteed that everyone supports it but there's no reason to change anything. eepp/ecode does not use by default this context given that the rendering path is slightly slower than using the default OpenGL one, given that drivers are very well optimized for the fixed-pipeline which is really bad for 3D apps but for 2D apps the fixed pipeline tends to be faster than programming your shaders by hand. So in short: eepp already supports modern OpenGL with programable-pipelines.
