### ISSUE TITLE
[premake] filters not reset a end of function

### ISSUE THREAD

**Issue by Jarod42** [SpartanJ/eepp#79]
Functions such as `build_eepp` do

```
	build_link_configuration( build_name ) -- use several filters

	cppdialect "C++17" -- only applies to last filter of `build_link_configuration`
```

`build_link_configuration` (and some other function) should reset filter at the end:

```
function build_link_configuration( package_name, use_ee_icon )
  filter "..."
  -- [..]

  filter {} -- Add that
end
```

**Comment by SpartanJ** [comment]
Oh! Thanks for pointing it out! I'll fix it. Crazy I didn't have any problems.

**Comment by SpartanJ** [comment]
Oh, first commit I missed reseting the filters after a project. I just read the documentation and I need to reset them always. I pushed another [fixes](https://github.com/SpartanJ/eepp/commit/2915d8081a5b87cd581e47617bdf5fdbf9b0c362).

**Comment by SpartanJ** [comment]
Oh I missed this:

Filters can be viewed as a scoping concept. A currently set filter goes 'out of scope' when either a filter reset operation is invoked or a project definition is started.

projects do reset, my bad.
